Autocompletion for Class Code Text Box
Marauders-9998/Attendance-Management-using-Face-Recognition pull request #29
Opened 2020-12-12 14:09 UTC by NiharikaVadlamudi

2020-12-12 18:59 UTC, Vibhu-Agarwal requested changes
![AMFR_auto_complete_bug](https://i.ibb.co/5jLJRVn/AMFR-Auto-complete-text-box.png)

Found these issues:
- Two and overlapping text-boxes for the class-code
  - one, just like the current one
  - other, new one, with auto-completion
- Text-box for entering Username has been removed

Issues, specifically related to auto-completion:
- After the auto-completion, the cursor remains at the point till where we typed.
  Ideally, auto-completion in CLI tools happens on the press of a `Tab` and we always expect the cursor to be at the end of the last character.
  This is highly opinionated though. If you agree with my point, you can make appropriate changes.

And rest of the issues have been pointed out in comments.

2020-12-12 18:59 UTC, Vibhu-Agarwal commented on Attendance_app.py
> +
Fix [PEP8](https://www.python.org/dev/peps/pep-0008/) Issues:
```
./Attendance_app.py:196:1: W293 blank line contains whitespace
./Attendance_app.py:200:24: E225 missing whitespace around operator
./Attendance_app.py:201:31: F405 'StringVar' may be undefined,
                                  or defined from star imports: tkinter
./Attendance_app.py:202:36: E261 at least two spaces before inline comment
./Attendance_app.py:203:22: E225 missing whitespace around operator
./Attendance_app.py:203:36: E231 missing whitespace after ','
./Attendance_app.py:207:34: E225 missing whitespace around operator
./Attendance_app.py:207:55: E225 missing whitespace around operator
./Attendance_app.py:209:1: W293 blank line contains whitespace
```

2020-12-12 18:59 UTC, Vibhu-Agarwal commented on Attendance_app.py
Fix [PEP8](https://www.python.org/dev/peps/pep-0008/) Issues:
```
./Attendance_app.py:271:1: W293 blank line contains whitespace
./Attendance_app.py:272:36: W291 trailing whitespace
./Attendance_app.py:274:13: E117 over-indented
./Attendance_app.py:279:24: W291 trailing whitespace
./Attendance_app.py:281:23: E231 missing whitespace after ','
./Attendance_app.py:282:13: E117 over-indented
./Attendance_app.py:283:23: E225 missing whitespace around operator
./Attendance_app.py:286:22: E231 missing whitespace after ','
./Attendance_app.py:287:13: E117 over-indented
./Attendance_app.py:291:28: E231 missing whitespace after ','
./Attendance_app.py:291:36: W291 trailing whitespace
./Attendance_app.py:292:13: E117 over-indented
./Attendance_app.py:301:1: E303 too many blank lines (4)
```

2020-12-12 18:59 UTC, Vibhu-Agarwal commented on Attendance_app.py
> +from tkinter import ttk
Fix [PEP8](https://www.python.org/dev/peps/pep-0008/) Issues:
```
./Attendance_app.py:20:1: F811 redefinition of unused 'tk' from line 5
./Attendance_app.py:21:1: F401 'tkinter.filedialog as tkfd' imported but unused
./Attendance_app.py:22:1: F403 'from tkinter import *' used;
                                unable to detect undefined names
./Attendance_app.py:23:1: F401 'tkinter.ttk' imported but unused
./Attendance_app.py:23:24: W291 trailing whitespace
```

2020-12-12 18:59 UTC, Vibhu-Agarwal commented on Attendance_app.py
> -        self.tv_username.place(x=340 * scale_factor, y=215 * scale_factor)
Accidentally deleted these lines?

2020-12-12 18:59 UTC, Vibhu-Agarwal commented on Attendance_app.py
> +        self.tv_class.place(x=400* scale_factor, y=160* scale_factor)
Initialization, focussing and placement have been done twice.
Also done on these lines:
https://github.com/Marauders-9998/Attendance-Management-using-Face-Recognition/blob/866f0cf26a3b5b11f0c13d4c08bc211f2e8feef5/Attendance_app.py#L186-L188

2020-12-13 09:31 UTC, NiharikaVadlamudi commented
@Vibhu-Agarwal  Pushed the wrong file before, apologies for that, couldn't fix the cursor issue, but I do agree with your suggestions on how it should function.

2020-12-13 18:40 UTC, Vibhu-Agarwal requested changes
@NiharikaVadlamudi Please go to the [`File changed`](https://github.com/Marauders-9998/Attendance-Management-using-Face-Recognition/pull/29/files) tab and self-review the PR once.
It seems that the whole file is changed. I'm unable to spot the exact (and intended) changes made in this PR.

Hint: It seems you're using a different code-formatter than the repository's [prefrred one](https://black.readthedocs.io/en/stable/).
The README also has a badge for it ;)

2020-12-14 09:29 UTC, closed without merging