Autocomplete Revised
Marauders-9998/Attendance-Management-using-Face-Recognition pull request #39
Opened 2020-12-29 19:49 UTC by NiharikaVadlamudi

1. Resolved Tkinter * imports.
2.  Reason behind changing from 340 to 400: The boxes overlapped in the previous case ( Now I set it to 380, looks fine)
3. Changes variable name to make it more meaningful.

2020-12-30 09:38 UTC, Vibhu-Agarwal requested changes

2020-12-30 09:38 UTC, Vibhu-Agarwal commented on Attendance_app.py
> +        self.classCodes =class_codes
⚠️ `E225 missing whitespace around operator.`
Forgot to apply code formatter?

⚠️ `camelCase usage for variable name`
Please use snake_case for variable names.

2020-12-30 09:38 UTC, Vibhu-Agarwal commented on Attendance_app.py
> +        classVar = self.class_variable.get()
⚠️ `camelCase usage for variable name`
Please use snake_case for variable names.

2020-12-30 09:38 UTC, Vibhu-Agarwal commented on Attendance_app.py
> +        self.tv_class.place(x=380 * scale_factor, y=160 * scale_factor)
👉 The placement of text-boxes has got to be uniform on a screen.
If they are overlapping, it's a separate issue which you can raise on GitHub.
For now, keep in line with the rest of the text-boxes.

2021-01-02 12:41 UTC, NiharikaVadlamudi commented
@Vibhu-Agarwal Please review the code now.

2021-01-03 10:21 UTC, Vibhu-Agarwal approved these changes

2021-01-03 10:26 UTC, merged